spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
  profiles:
    active: ${PROFILE}
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: Asia/Seoul
  application:
    name: v1-oauth-service
  config:
    import: ${CLOUD_CONFIG_IMPORT_URL:optional:configserver:https://api.xquare.app/cloud-config/}
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
  data:
    redis:
      port: 6379
      host: redis.xquare.app

oauth:
  token:
    access-token-expiration-by-hour: ${OAUTH_ACCESS_TOKEN_EXP:1}
    refresh-token-expiration-by-day: ${OAUTH_REFRESH_TOKEN_EXP:14}

server:
  shutdown: graceful
